Repository DEFRA/waste-carriers-front-office, pull requests merged in 2019-03, with the labels that each got.

#198 Unlock Rails version
  Gemfile
  Gemfile.lock
Labels: housekeeping

#207 Fix Airbrake for the dev environment
  config/initializers/airbrake.rb
Labels: bug

#211 Update privacy policy
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/partials/_published_dates.scss
  app/views/pages/privacy.html.erb
Labels: enhancement

#214 Change 'don't' to 'do not'
  app/views/pages/privacy.html.erb
Labels: bug
