Repository DEFRA/waste-carriers-front-office, pull requests merged in 2019-01, with the labels that each got.

#154 Install defra-ruby-style for linting
  .rubocop.yml
  Gemfile
  Gemfile.lock
Labels: housekeeping

#156 Make dashboard links more accessible
  app/views/dashboards/index.html.erb
  config/locales/dashboards.en.yml
Labels: enhancement

#159 Get defra-ruby-style from Rubygems
  Gemfile
  Gemfile.lock
Labels: dependencies

#161 Add unique ID to div around each registration
  app/views/dashboards/index.html.erb
Labels: enhancement

#165 Don't list inactive registrations on dashboard
  app/controllers/dashboards_controller.rb
  spec/requests/dashboards_spec.rb
Labels: bug

#167 Fixed line width and refactored related sass partial
  app/assets/stylesheets/partials/_dashboard.scss
Labels: bug
