Repository DEFRA/waste-carriers-front-office, pull requests merged in 2020-03, with the labels that each got.

#420 Remove delete link from user dashboard
  app/helpers/dashboards_helper.rb
  app/views/dashboards/index.html.erb
  spec/helpers/dashboards_helper_spec.rb
Labels: housekeeping

#421 Remove Order copy cards link
  app/helpers/dashboards_helper.rb
  app/views/dashboards/index.html.erb
  spec/helpers/dashboards_helper_spec.rb
Labels: housekeeping

#427 Switch to SonarCloud from CodeClimate
  .travis.yml
  README.md
  sonar-project.properties
Labels: housekeeping

#433 Hide start new registration behind feature toggle
  Gemfile.lock
  config/feature_toggles.yml
Labels: housekeeping

#434 Add charge value for New registrations
  config/application.rb
Labels: enhancement

#440 Use sequence to generate reg_identifier
  spec/factories/registration.rb
Labels: bug

#448 Add style for blue application received box
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/partials/_govuk-box-highlight.scss
Labels: enhancement
