Repository DEFRA/waste-carriers-front-office, pull requests merged in 2020-07, with the labels that each got.

#557 Changes need to support switch to 'main' branch
  Gemfile
  Gemfile.lock
  README.md
Labels: housekeeping

#559 Update dashboard 'change password' link
  app/controllers/passwords_controller.rb
  app/helpers/dashboards_helper.rb
  app/views/passwords/edit.html.erb
  config/locales/en.yml
  config/locales/passwords.en.yml
  config/routes.rb
  spec/helpers/dashboards_helper_spec.rb
  spec/requests/passwords_spec.rb
Labels: enhancement

#569 Update defra-ruby-alert to use blocklist
  Gemfile.lock
  config/initializers/waste_carriers_engine.rb
Labels: housekeeping

#570 Remove link to certificate from renewal complete
  Gemfile.lock
Labels: enhancement

#571 Redirect to /fo after password reset
  app/controllers/passwords_controller.rb
  spec/requests/passwords_spec.rb
Labels: bug

#572 Direct 'New registration' btn based on ft. toggle
  app/helpers/dashboards_helper.rb
  spec/helpers/dashboards_helper_spec.rb
Labels: enhancement

#574 Allow individual pages to include page_scripts
  app/views/layouts/application.html.erb
Labels: enhancement

#578 Tell engine we are the front-office
  Gemfile.lock
  config/initializers/waste_carriers_engine.rb
Labels: enhancement

#580 Update payment confirmation behaviour
  Gemfile.lock
Labels: enhancement

#581 Do not copy receipt_email when init. renewal
  Gemfile.lock
Labels: bug
