Repository DEFRA/waste-carriers-front-office, pull requests merged in 2020-01, with the labels that each got.

#359 Add finance details to registrations
  db/seeds/CBDU200.json
  db/seeds/CBDU201.json
  db/seeds/CBDU202.json
  db/seeds/CBDU203.json
  db/seeds/CBDU204.json
  db/seeds/CBDU205.json
  db/seeds/CBDU206.json
  db/seeds/CBDU207.json
  db/seeds/CBDU208.json
  db/seeds/CBDU209.json
  db/seeds/CBDU210.json
  db/seeds/CBDU211.json
  db/seeds/CBDU212.json
  db/seeds/CBDU213.json
  db/seeds/CBDU214.json
  db/seeds/CBDU215.json
  db/seeds/CBDU216.json
  db/seeds/CBDU217.json
  db/seeds/CBDU218.json
  db/seeds/CBDU219.json
  db/seeds/CBDU220.json
  db/seeds/CBDU221.json
  db/seeds/CBDU222.json
  db/seeds/CBDU223.json
  db/seeds/CBDU224.json
  db/seeds/CBDU225.json
  db/seeds/CBDU226.json
  db/seeds/CBDU227.json
  db/seeds/CBDU228.json
  db/seeds/CBDU229.json
  db/seeds/CBDU230.json
  db/seeds/CBDU231.json
  db/seeds/CBDU232.json
  db/seeds/CBDU233.json
  db/seeds/CBDU234.json
Labels: housekeeping

#369 Read companies house url from environment
  config/initializers/waste_carriers_engine.rb
Labels: bug

#373 Update mocks engine to support Worldpay
  Gemfile
  Gemfile.lock
  config/application.rb
  config/initializers/defra_ruby_mocks.rb
Labels: enhancement

#375 Update mock engine to get Worldpay refund support
  Gemfile
  Gemfile.lock
Labels: enhancement

#381 Fix broken 'Finished' link on renewal end pages
  Gemfile.lock
  app/helpers/waste_carriers_engine/journey_links_helper.rb
  spec/helpers/waste_carriers_engine/journey_links_helper_spec.rb
Labels: bug

#384 Temp. fix for cc-test-reporter & SimpleCov 0.18
  Gemfile
  Gemfile.lock
Labels: housekeeping
