Repository DEFRA/waste-carriers-front-office, pull requests merged in 2020-04, with the labels that each got.

#482 Remove Edit link from dashboard search results
  app/helpers/dashboards_helper.rb
  app/views/dashboards/index.html.erb
  spec/helpers/dashboards_helper_spec.rb
Labels: enhancement

#484 Fix json dependency security issue
  Gemfile
  Gemfile.lock
Labels: dependencies, security

#493 Fix SonarCloud code coverage reporting
  Gemfile
  Gemfile.lock
Labels: bug

#496 Use multiple rubocop formats in Travis build
  .travis.yml
Labels: housekeeping

#500 Add configs for defra ruby address gem
  config/initializers/waste_carriers_engine.rb
Labels: enhancement
